parameters:
    hcaptcha_site_key: '%env(HCAPTCHA_SITE_KEY)%'
    hcaptcha_secret_key: '%env(HCAPTCHA_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\SecurityController:
        arguments:
            $hcaptchaSiteKey: '%hcaptcha_site_key%'
            $hcaptchaSecretKey: '%hcaptcha_secret_key%'


    App\Controller\InsuranceAssistantController:
        arguments:
            $fastapiUrl: '%env(FASTAPI_URL)%'